from enum import StrEnum


class ErrorCode(StrEnum):
    UNAUTHORIZED = "UNAUTHORIZED"
    INVALID_TOKEN = "INVALID_TOKEN"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    CONFLICT = "CONFLICT"

    DUPLICATE_PENDING_REQUEST = "DUPLICATE_PENDING_REQUEST"
    TEAM_ROLE_FORBIDDEN = "TEAM_ROLE_FORBIDDEN"
    TEAM_OWNER_IMMUTABLE = "TEAM_OWNER_IMMUTABLE"
    TEAM_TRANSFER_INVALID = "TEAM_TRANSFER_INVALID"

    MATCH_TEAM_DUPLICATED = "MATCH_TEAM_DUPLICATED"
    MATCH_STATUS_INVALID_TRANSITION = "MATCH_STATUS_INVALID_TRANSITION"
    ROSTER_INVALID_MEMBER = "ROSTER_INVALID_MEMBER"
    ROSTER_INVALID_POSITION = "ROSTER_INVALID_POSITION"

    APPLE_TOKEN_INVALID = "APPLE_TOKEN_INVALID"
    DEBUG_TOKEN_DISABLED = "DEBUG_TOKEN_DISABLED"
