included:
  - BianLunMiao
  - BianLunMiaoTests
  - BianLunMiaoUITests

excluded:
  - build
  - docs
  - fal_inputs

disabled_rules:
  - trailing_whitespace
  - line_length
  - file_length
  - type_body_length
  - function_body_length
  - cyclomatic_complexity
  - force_cast
  - force_try
  - large_tuple
  - todo

opt_in_rules:
  - empty_count
  - first_where
  - sorted_first_last

identifier_name:
  min_length:
    warning: 1
    error: 1
  excluded:
    - id
    - x
    - y

reporter: xcode
